
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 28 19:50:52 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 6;
  public static final int GE = 20;
  public static final int CASE = 17;
  public static final int LPAREN = 39;
  public static final int SEMI = 34;
  public static final int CONTINUE = 13;
  public static final int FOR = 14;
  public static final int MINUS = 29;
  public static final int CHARACTER = 47;
  public static final int RPAREN = 40;
  public static final int AND = 22;
  public static final int LT = 27;
  public static final int OR = 23;
  public static final int BOOL = 48;
  public static final int QMARK = 38;
  public static final int COMMA = 36;
  public static final int INC = 24;
  public static final int DIV = 31;
  public static final int PLUS = 28;
  public static final int IF = 7;
  public static final int DOT = 37;
  public static final int LE = 21;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int EQUAL = 33;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int MUL = 30;
  public static final int EQEQ = 18;
  public static final int NUMBER = 46;
  public static final int MOD = 32;
  public static final int IDENT = 45;
  public static final int BREAK = 3;
  public static final int VOID = 12;
  public static final int LBRACK = 41;
  public static final int SWITCH = 16;
  public static final int COLON = 35;
  public static final int LBRACE = 43;
  public static final int ELSE = 5;
  public static final int RBRACK = 42;
  public static final int ENUM = 4;
  public static final int READ = 10;
  public static final int RBRACE = 44;
  public static final int PROG = 2;
  public static final int NE = 19;
  public static final int DEC = 25;
  public static final int GT = 26;
  public static final int PRINT = 9;
  public static final int LENGTH = 15;
}

