
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 17 19:20:06 UTC 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 6;
  public static final int GE = 19;
  public static final int CASE = 16;
  public static final int HASH = 44;
  public static final int LPAREN = 38;
  public static final int SEMI = 33;
  public static final int CONTINUE = 12;
  public static final int FOR = 13;
  public static final int MINUS = 28;
  public static final int CHARACTER = 48;
  public static final int RPAREN = 39;
  public static final int AND = 21;
  public static final int LT = 26;
  public static final int OR = 22;
  public static final int BOOL = 49;
  public static final int QMARK = 37;
  public static final int COMMA = 35;
  public static final int INC = 23;
  public static final int DIV = 30;
  public static final int PLUS = 27;
  public static final int IF = 7;
  public static final int DOT = 36;
  public static final int LE = 20;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 32;
  public static final int NEW = 45;
  public static final int error = 1;
  public static final int MUL = 29;
  public static final int EQEQ = 17;
  public static final int NUMBER = 47;
  public static final int MOD = 31;
  public static final int IDENT = 46;
  public static final int BREAK = 3;
  public static final int VOID = 11;
  public static final int LBRACK = 40;
  public static final int SWITCH = 15;
  public static final int COLON = 34;
  public static final int LBRACE = 42;
  public static final int ELSE = 5;
  public static final int RBRACK = 41;
  public static final int ENUM = 4;
  public static final int READ = 9;
  public static final int RBRACE = 43;
  public static final int PROG = 2;
  public static final int NE = 18;
  public static final int DEC = 24;
  public static final int GT = 25;
  public static final int PRINT = 8;
  public static final int LENGTH = 14;
}

